Repository delphi-hub/delphi-registry, pull requests merged in 2018-11, with the labels that each got.

#31 The README file now contains a proper description of the registry
  README.md
Labels: enhancement

#33 Added data model representation for links between instances
  OpenAPISpecification.yaml
  README.md
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/Configuration.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/Docker/ContainerCommands.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/Docker/DockerActor.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/RequestHandler.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/connection/Server.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/daos/DynamicInstanceDAO.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/daos/InstanceDAO.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/io/swagger/client/model/Event.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/io/swagger/client/model/Instance.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/io/swagger/client/model/InstanceLink.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/io/swagger/client/model/InstanceNetwork.scala
  src/test/scala/de/upb/cs/swt/delphi/instanceregistry/RequestHandlerTest.scala
  src/test/scala/de/upb/cs/swt/delphi/instanceregistry/daos/DynamicInstanceDAOTest.scala
Labels: enhancement

#40 Increased default docker operation timeout
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/Configuration.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/RequestHandler.scala
Labels: bug, enhancement

#42 Fixed semantics of the /stop endpoint
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/RequestHandler.scala
Labels: bug

#46 Fixed bugs in endpoint /assignInstance
  OpenAPISpecification.yaml
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/Docker/ContainerCommands.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/connection/Server.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/io/swagger/client/model/Event.scala
Labels: bug

#41 Feature/container command docker
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/Docker/ContainerCommands.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/Docker/DockerActor.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/Docker/PostDataFormatting.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/RequestHandler.scala
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/connection/Server.scala
Labels: enhancement

#51 Fixed server returning 500 on malformed JSON input
  src/main/scala/de/upb/cs/swt/delphi/instanceregistry/connection/Server.scala
Labels: bug
